### ISSUE TITLE
길찾기 ANR 이슈

### ISSUE THREAD

**Issue by HS-JNYLee** [KJH0506/Naver_Navi_TeamProject#85]
![image](https://github.com/user-attachments/assets/c0b1add7-cbce-4aff-9548-f963a83534fb)
브랜치 : feature/pedestrian-mapping (develop 머지 이후 이슈 발생)
출발지 : 광화문 미도파
도착지 : 한성대학교

1. 1번째 경로 클릭
2.  세부 경로 클릭

>> 이슈 : 지도가 어딘가로 포커싱되면서 렌더링하다가 멈춤.

**Comment by HS-JNYLee** [comment]
@junni01kim 
avd 위치를 시청으로 하고 진행
출발 : 시청
도착 : 한성대학교

이슈 > 내 위치 마커 업데이트 이후 시작 부분 보행자 경로가 사라짐
(마커 업데이트 직전까지는 잘나옴)

![image](https://github.com/user-attachments/assets/263fdd03-3803-4eac-9f1a-53499ed53d79)

**Comment by junni01kim** [comment]
해결되셨나용

**Comment by junni01kim** [comment]
해결됐대요
